/**
 * Pure markdown renderer for the tickets.export snapshot.
 *
 * renderExportMarkdown() is a pure function — it takes all inputs explicitly
 * and never calls Date or nowIso(). Pass exportedAt from the caller.
 */

export interface TicketRelationEntry {
  id: string;
  note: string | null;
}

export interface TicketRelations {
  outgoing: Record<string, Array<TicketRelationEntry>>;
  incoming: Record<string, Array<TicketRelationEntry>>;
}

export interface TicketRecord {
  id: string;
  title: string;
  description: string;
  status: string;
  priority: string | null;
  type: string;
  effort: number | null;
  epic: string | null;
  tags: string[];
  relations: TicketRelations;
}

export interface ExportRenderInput {
  projectId: string;
  exportedAt: string;
  tickets: TicketRecord[];
  statusCounts: Record<string, number>;
}

// ---------------------------------------------------------------------------
// Priority bucketing
// Known rank: P0→0, P1→1, P2→2, P3→3, null→4, other→5
// ---------------------------------------------------------------------------

const KNOWN_PRIORITY_RANK: Record<string, number> = { P0: 0, P1: 1, P2: 2, P3: 3 };

// ---------------------------------------------------------------------------
// Per-ticket renderer
// ---------------------------------------------------------------------------

function renderTicket(ticket: TicketRecord): string {
  const lines: string[] = [];

  // Heading
  lines.push(`### ${ticket.id} — ${ticket.title}`);

  // Compact field line — only non-empty fields
  const fields: string[] = [];
  fields.push(`**Status:** ${ticket.status}`);
  fields.push(`**Type:** ${ticket.type}`);
  if (ticket.effort !== null) fields.push(`**Effort:** ${ticket.effort}`);
  if (ticket.epic !== null) fields.push(`**Epic:** ${ticket.epic}`);
  if (ticket.tags.length > 0) fields.push(`**Tags:** ${ticket.tags.join(", ")}`);
  lines.push(fields.join(" · "));

  // Relations block
  const incomingBlocks = ticket.relations.incoming["blocks"] ?? [];
  const blockerIds = incomingBlocks.map((e) => e.id);

  // All other relation entries (everything except incoming blocks)
  const otherRelations: Array<{ direction: "outgoing" | "incoming"; kind: string; entry: TicketRelationEntry }> = [];

  for (const [kind, entries] of Object.entries(ticket.relations.outgoing)) {
    for (const entry of entries) {
      otherRelations.push({ direction: "outgoing", kind, entry });
    }
  }
  for (const [kind, entries] of Object.entries(ticket.relations.incoming)) {
    if (kind === "blocks") continue; // handled as Blockers line
    for (const entry of entries) {
      otherRelations.push({ direction: "incoming", kind, entry });
    }
  }

  if (blockerIds.length > 0 || otherRelations.length > 0) {
    lines.push("");
    if (blockerIds.length > 0) {
      lines.push(`**Blockers:** ${blockerIds.join(", ")}`);
    }
    if (otherRelations.length > 0) {
      lines.push("**Relations:**");
      for (const { kind, entry } of otherRelations) {
        const notePart = entry.note !== null ? ` (${entry.note})` : "";
        lines.push(`- ${kind}: ${entry.id}${notePart}`);
      }
    }
  }

  // Description verbatim (blank line separator)
  lines.push("");
  lines.push(ticket.description);

  return lines.join("\n");
}

// ---------------------------------------------------------------------------
// Main renderer
// ---------------------------------------------------------------------------

export function renderExportMarkdown(input: ExportRenderInput): string {
  const { projectId, exportedAt, tickets, statusCounts } = input;
  const parts: string[] = [];

  // 1. Banner
  parts.push(
    "<!-- GENERATED BY ticketgraph — DO NOT EDIT BY HAND. Source of truth is the ticketgraph DB. -->",
  );
  parts.push("");
  parts.push(
    `> **Exported ${exportedAt}** from the ticketgraph DB (project \`${projectId}\`, ${tickets.length} tickets). The DB is the source of truth; this file is a point-in-time snapshot and *will* drift. Re-run \`tickets.export\` to refresh.`,
  );

  // 2. Counts line
  const c = (key: string) => statusCounts[key] ?? 0;
  parts.push("");
  parts.push(
    `**${tickets.length} tickets** — open: ${c("open")}, in_progress: ${c("in_progress")}, blocked: ${c("blocked")}, done: ${c("done")}, deferred: ${c("deferred")}`,
  );

  // 3. Group tickets by priority bucket
  // Bucket key: "P0" | "P1" | "P2" | "P3" | null (no-priority) | other string
  type BucketKey = string | null;

  const buckets = new Map<BucketKey, TicketRecord[]>();

  for (const ticket of tickets) {
    const key: BucketKey = ticket.priority;
    if (!buckets.has(key)) buckets.set(key, []);
    buckets.get(key)!.push(ticket);
  }

  // Sort within each bucket by id (plain string sort)
  for (const [, arr] of buckets) {
    arr.sort((a, b) => (a.id < b.id ? -1 : a.id > b.id ? 1 : 0));
  }

  // Build ordered list of bucket keys
  // Known order: P0, P1, P2, P3, null, then unknown values sorted by string
  const knownOrder: BucketKey[] = ["P0", "P1", "P2", "P3", null];
  const unknownKeys: string[] = [];
  for (const key of buckets.keys()) {
    if (key !== null && !(key in KNOWN_PRIORITY_RANK)) {
      unknownKeys.push(key);
    }
  }
  unknownKeys.sort();

  const orderedKeys: BucketKey[] = [...knownOrder, ...unknownKeys];

  // Render each non-empty bucket
  for (const key of orderedKeys) {
    if (!buckets.has(key)) continue;
    const heading = key === null ? "## (no priority)" : key in KNOWN_PRIORITY_RANK ? `## ${key}` : `## (other: ${key})`;
    parts.push("");
    parts.push(heading);
    for (const ticket of buckets.get(key)!) {
      parts.push("");
      parts.push(renderTicket(ticket).replace(/\n+$/, ""));
    }
  }

  return parts.join("\n");
}
