import { describe, it, expect } from "vitest";
import { renderExportMarkdown } from "./export-markdown.js";
import type { TicketRecord, ExportRenderInput } from "./export-markdown.js";

// ---------------------------------------------------------------------------
// Fixtures
// ---------------------------------------------------------------------------

function makeTicket(overrides: Partial<TicketRecord> & { id: string; title: string }): TicketRecord {
  return {
    description: "",
    status: "open",
    priority: "P1",
    type: "task",
    effort: null,
    epic: null,
    tags: [],
    relations: { outgoing: {}, incoming: {} },
    ...overrides,
  };
}

const BASE_INPUT: ExportRenderInput = {
  projectId: "demo",
  exportedAt: "2026-05-30T12:00:00.000Z",
  tickets: [
    makeTicket({ id: "T1", title: "First task", priority: "P0" }),
    makeTicket({ id: "T2", title: "Second task", priority: "P1" }),
  ],
  statusCounts: { open: 2 },
};

// ---------------------------------------------------------------------------
// Tests
// ---------------------------------------------------------------------------

describe("renderExportMarkdown", () => {
  it("opens with the DO-NOT-EDIT comment then a timestamped banner naming project and count", () => {
    const out = renderExportMarkdown(BASE_INPUT);
    const lines = out.split("\n");

    // Line 0: HTML comment
    expect(lines[0]).toBe(
      "<!-- GENERATED BY ticketgraph — DO NOT EDIT BY HAND. Source of truth is the ticketgraph DB. -->",
    );

    // Line 1: blank
    expect(lines[1]).toBe("");

    // Line 2: blockquote banner
    expect(lines[2]).toContain("> **Exported 2026-05-30T12:00:00.000Z**");
    expect(lines[2]).toContain("project `demo`");
    expect(lines[2]).toContain("2 tickets");
    expect(lines[2]).toContain("tickets.export");
  });

  it("renders the status counts line", () => {
    const input: ExportRenderInput = {
      ...BASE_INPUT,
      statusCounts: { open: 3, in_progress: 1, blocked: 0, done: 5, deferred: 2 },
    };
    const out = renderExportMarkdown(input);
    expect(out).toContain("**2 tickets**");
    expect(out).toContain("open: 3");
    expect(out).toContain("in_progress: 1");
    expect(out).toContain("blocked: 0");
    expect(out).toContain("done: 5");
    expect(out).toContain("deferred: 2");
  });

  it("renders every ticket grouped by priority with P0..P3 then no-priority", () => {
    const input: ExportRenderInput = {
      projectId: "demo",
      exportedAt: "2026-05-30T00:00:00.000Z",
      tickets: [
        makeTicket({ id: "T3", title: "Medium", priority: "P2" }),
        makeTicket({ id: "T1", title: "Critical", priority: "P0" }),
        makeTicket({ id: "T2", title: "High", priority: "P1" }),
        makeTicket({ id: "T4", title: "No pri", priority: null }),
        makeTicket({ id: "T5", title: "Low", priority: "P3" }),
      ],
      statusCounts: { open: 5 },
    };
    const out = renderExportMarkdown(input);

    // Sections appear in rank order
    const p0Pos = out.indexOf("## P0");
    const p1Pos = out.indexOf("## P1");
    const p2Pos = out.indexOf("## P2");
    const p3Pos = out.indexOf("## P3");
    const noPriPos = out.indexOf("## (no priority)");

    expect(p0Pos).toBeGreaterThan(-1);
    expect(p1Pos).toBeGreaterThan(p0Pos);
    expect(p2Pos).toBeGreaterThan(p1Pos);
    expect(p3Pos).toBeGreaterThan(p2Pos);
    expect(noPriPos).toBeGreaterThan(p3Pos);

    // T1 appears under P0, T3 under P2
    const p0Section = out.slice(p0Pos, p1Pos);
    expect(p0Section).toContain("### T1");
    const p2Section = out.slice(p2Pos, p3Pos);
    expect(p2Section).toContain("### T3");

    // Tickets within a section are id-sorted (string sort)
    const p1Section = out.slice(p1Pos, p2Pos);
    expect(p1Section).toContain("### T2");
  });

  it("renders status, type, effort, epic, tags and omits empty fields", () => {
    const full = makeTicket({
      id: "T10",
      title: "Full ticket",
      status: "in_progress",
      type: "bug",
      effort: 5,
      epic: "Foundation",
      tags: ["alpha", "beta"],
      priority: "P1",
    });
    const minimal = makeTicket({
      id: "T11",
      title: "Minimal ticket",
      status: "open",
      type: "task",
      priority: "P1",
      // effort null, epic null, tags []
    });

    const out = renderExportMarkdown({
      projectId: "x",
      exportedAt: "2026-05-30T00:00:00.000Z",
      tickets: [full, minimal],
      statusCounts: { in_progress: 1, open: 1 },
    });

    // Full ticket shows all fields
    expect(out).toContain("**Status:** in_progress");
    expect(out).toContain("**Type:** bug");
    expect(out).toContain("**Effort:** 5");
    expect(out).toContain("**Epic:** Foundation");
    expect(out).toContain("**Tags:** alpha, beta");

    // Minimal ticket omits effort, epic, tags
    const t11Pos = out.indexOf("### T11");
    const afterT11 = out.slice(t11Pos, t11Pos + 300);
    expect(afterT11).not.toContain("**Effort:**");
    expect(afterT11).not.toContain("**Epic:**");
    expect(afterT11).not.toContain("**Tags:**");
  });

  it("reproduces description verbatim", () => {
    const desc = "Line one\n\n> blockquote\n\n- item\n  - nested\n\n```ts\nconst x = 1;\n```\n";
    const ticket = makeTicket({ id: "T1", title: "Desc test", description: desc, priority: "P0" });
    const out = renderExportMarkdown({
      projectId: "x",
      exportedAt: "2026-05-30T00:00:00.000Z",
      tickets: [ticket],
      statusCounts: { open: 1 },
    });
    // Trailing newline from description is trimmed at render boundary to avoid
    // double blank lines; check content without the trailing newline.
    expect(out).toContain(desc.trimEnd());
  });

  it("renders incoming blocks as a Blockers line and other kinds under Relations", () => {
    // T2 is blocked by T1 (incoming blocks on T2's side)
    // T2 relates_to T3 (outgoing)
    const t2 = makeTicket({
      id: "T2",
      title: "Blocked ticket",
      priority: "P1",
      relations: {
        incoming: {
          blocks: [{ id: "T1", note: null }],
        },
        outgoing: {
          relates_to: [{ id: "T3", note: "related work" }],
        },
      },
    });

    const out = renderExportMarkdown({
      projectId: "x",
      exportedAt: "2026-05-30T00:00:00.000Z",
      tickets: [t2],
      statusCounts: { open: 1 },
    });

    expect(out).toContain("**Blockers:** T1");
    expect(out).toContain("**Relations:**");
    expect(out).toContain("- relates_to: T3 (related work)");
  });

  it("buckets an unknown priority value into an (other: …) section, never drops it", () => {
    const input: ExportRenderInput = {
      projectId: "x",
      exportedAt: "2026-05-30T00:00:00.000Z",
      tickets: [
        makeTicket({ id: "T1", title: "Normal", priority: "P0" }),
        makeTicket({ id: "T2", title: "Future prio", priority: "P4" }),
        makeTicket({ id: "T3", title: "Critical label", priority: "critical" }),
      ],
      statusCounts: { open: 3 },
    };
    const out = renderExportMarkdown(input);

    // P4 and critical go to (other: …) sections — never dropped
    expect(out).toContain("## (other: P4)");
    expect(out).toContain("## (other: critical)");
    expect(out).toContain("### T2");
    expect(out).toContain("### T3");

    // Unknown sections appear after P3 / no-priority
    const p0Pos = out.indexOf("## P0");
    const p4Pos = out.indexOf("## (other: P4)");
    const critPos = out.indexOf("## (other: critical)");
    expect(p4Pos).toBeGreaterThan(p0Pos);
    expect(critPos).toBeGreaterThan(p0Pos);

    // Unknown values ordered by value string: "P4" < "critical"
    expect(p4Pos).toBeLessThan(critPos);
  });

  it("sorts tickets within a priority section by id ascending", () => {
    const out = renderExportMarkdown({
      projectId: "x",
      exportedAt: "2026-05-30T00:00:00.000Z",
      tickets: [
        makeTicket({ id: "T3", title: "Third",  priority: "P1" }),
        makeTicket({ id: "T1", title: "First",  priority: "P1" }),
        makeTicket({ id: "T2", title: "Second", priority: "P1" }),
      ],
      statusCounts: { open: 3 },
    });
    const p1Start = out.indexOf("## P1");
    const t1 = out.indexOf("### T1", p1Start);
    const t2 = out.indexOf("### T2", p1Start);
    const t3 = out.indexOf("### T3", p1Start);
    expect(t1).toBeLessThan(t2);
    expect(t2).toBeLessThan(t3);
  });

  it("renders cleanly with zero tickets", () => {
    const out = renderExportMarkdown({ projectId: "empty", exportedAt: "2026-05-30T00:00:00.000Z", tickets: [], statusCounts: {} });
    expect(out).toContain("0 tickets");
    expect(out).not.toContain("## ");
  });

  it("is deterministic: same input minus exportedAt yields identical body", () => {
    const tickets = [
      makeTicket({ id: "T1", title: "Alpha", priority: "P0" }),
      makeTicket({ id: "T2", title: "Beta", priority: null }),
    ];
    const statusCounts = { open: 2 };

    const out1 = renderExportMarkdown({
      projectId: "proj",
      exportedAt: "2026-01-01T00:00:00.000Z",
      tickets,
      statusCounts,
    });
    const out2 = renderExportMarkdown({
      projectId: "proj",
      exportedAt: "2099-12-31T23:59:59.999Z",
      tickets,
      statusCounts,
    });

    const lines1 = out1.split("\n");
    const lines2 = out2.split("\n");

    // Must have same number of lines
    expect(lines1.length).toBe(lines2.length);

    // Collect differing line indices
    const diffs: number[] = [];
    for (let i = 0; i < lines1.length; i++) {
      if (lines1[i] !== lines2[i]) diffs.push(i);
    }

    // ONLY the banner blockquote line may differ
    expect(diffs).toHaveLength(1);
    expect(lines1[diffs[0]!]).toMatch(/^> \*\*Exported/);
  });
});
