import { describe, it, expect, afterEach } from "vitest";
import fs from "node:fs";
import path from "node:path";
import os from "node:os";
import { openDb } from "../db.js";
import { makeExportTool } from "./export.js";

let tmpRoot: string;
let db: ReturnType<typeof openDb>["db"];

function setup() {
  tmpRoot = fs.mkdtempSync(path.join(os.tmpdir(), "tg-export-"));
  const { db: openedDb } = openDb({ path: path.join(tmpRoot, "test.db") });
  db = openedDb;

  db.prepare(
    "INSERT INTO projects (id, display_name, root_path, created_at) VALUES (?, ?, ?, ?)",
  ).run("proj1", "Project One", tmpRoot, "2026-01-01T00:00:00.000Z");

  return makeExportTool(db);
}

function insertTicket(id: string, priority: string | null = "P1") {
  db.prepare(
    `INSERT INTO tickets (id, project_id, title, description, status, priority, type, created_at)
     VALUES (?, ?, ?, ?, ?, ?, ?, ?)`,
  ).run(id, "proj1", `Title ${id}`, `Description of ${id}`, "open", priority, "feature", "2026-01-01T00:00:00.000Z");
}

afterEach(() => {
  db.close();
  fs.rmSync(tmpRoot, { recursive: true, force: true });
});

describe("tickets.export", () => {
  it("writes <root>/.ai/TICKETS.md and returns { path, bytes, ticket_count, exported_at }", async () => {
    const tool = setup();
    insertTicket("T1");
    insertTicket("T2");

    const result = await tool.handle(tool.parseArgs({ project: "proj1" }));

    expect(result.path.endsWith(".ai/TICKETS.md")).toBe(true);
    expect(result.path).toContain(os.tmpdir());
    expect(result.bytes).toBeGreaterThan(0);
    expect(result.ticket_count).toBe(2);
    expect(result.exported_at).toMatch(/^\d{4}-\d{2}-\d{2}T\d{2}:\d{2}:\d{2}\.\d{3}Z$/);
    expect(fs.existsSync(result.path)).toBe(true);
  });

  it("the written file opens with the DO-NOT-EDIT comment and the timestamped banner", async () => {
    const tool = setup();
    insertTicket("T1");

    const result = await tool.handle(tool.parseArgs({ project: "proj1" }));
    const content = fs.readFileSync(result.path, "utf-8");
    const lines = content.split("\n");

    expect(lines[0]).toBe(
      "<!-- GENERATED BY ticketgraph — DO NOT EDIT BY HAND. Source of truth is the ticketgraph DB. -->",
    );
    expect(content).toContain("> **Exported");
  });

  it("contains every ticket in the project grouped by priority", async () => {
    const tool = setup();
    insertTicket("T1", "P0");
    insertTicket("T2", "P1");
    insertTicket("T3", "P2");

    const result = await tool.handle(tool.parseArgs({ project: "proj1" }));
    const content = fs.readFileSync(result.path, "utf-8");

    expect(content).toContain("T1");
    expect(content).toContain("T2");
    expect(content).toContain("T3");
    // Priority headings
    expect(content).toContain("## P0");
    expect(content).toContain("## P1");
    expect(content).toContain("## P2");
  });

  it("absolute path override writes verbatim to the given path", async () => {
    const tool = setup();
    insertTicket("T1");
    const customPath = path.join(tmpRoot, "custom", "OUT.md");

    const result = await tool.handle(tool.parseArgs({ project: "proj1", path: customPath }));

    expect(result.path).toBe(customPath);
    expect(fs.existsSync(customPath)).toBe(true);
  });

  it("relative path override resolves under root_path, not cwd", async () => {
    const tool = setup();
    insertTicket("T1");

    const result = await tool.handle(tool.parseArgs({ project: "proj1", path: "sub/OUT.md" }));

    const expectedPath = path.join(tmpRoot, "sub", "OUT.md");
    expect(result.path).toBe(expectedPath);
    expect(fs.existsSync(expectedPath)).toBe(true);
  });

  it("re-exporting an unchanged DB overwrites the same file and changes only the banner timestamp line", async () => {
    const tool = setup();
    insertTicket("T1");

    const exportPath = path.join(tmpRoot, "out.md");

    await tool.handle(tool.parseArgs({ project: "proj1", path: exportPath }));
    const firstLines = fs.readFileSync(exportPath, "utf-8").split("\n");

    await tool.handle(tool.parseArgs({ project: "proj1", path: exportPath }));
    const secondLines = fs.readFileSync(exportPath, "utf-8").split("\n");

    // Same number of lines — confirms the file was overwritten in place, not appended
    expect(firstLines.length).toBe(secondLines.length);

    const differingLines = firstLines.filter((line, i) => line !== secondLines[i]);

    // At most one line differs, and if any, it must be the banner timestamp line
    expect(differingLines.length).toBeLessThanOrEqual(1);
    if (differingLines.length === 1) {
      expect(differingLines[0]).toMatch(/^> \*\*Exported/);
    }
  });
});
